# Import

In [18]:
import pandas as pd
from pycaret.classification import *
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing

# DataLoad

In [2]:
features12_tr = pd.read_csv('../3.로티로리_데이터 및 모델 세이브 파일/features12_tr.csv')
features3_te = pd.read_csv('../3.로티로리_데이터 및 모델 세이브 파일/features3_te.csv')

In [3]:
print(features12_tr.shape)
display(features12_tr)

(18638, 82)

,cust,mpd_nunique,favorite_pd,favorite_zon,favorite_loc,mean_buy_am,max_buy_am,num_visit,day_sum_buy_am,day_count_buy_am,buy_mean_end,buy_mean_middle,buy_mean_begin,buy_count_end,buy_count_middle,buy_count_begin,buy_cycle,visit_weekend_ratio,fri_mean,mon_mean,sat_mean,sun_mean,thu_mean,tue_mean,wed_mean,fri_count,mon_count,sat_count,sun_count,thu_count,tue_count,wed_count,most_buying_day,most_buying_hour,most_buying_weekday,most_expensive,off_hot_time_buy_am,off_hot_time_buy_count,on_hot_time_buy_am,on_hot_time_buy_count,mean_temperature,mean_huminity,mean_rainfall,mean_atmosphere,pdde_chnl_diversity,pdde_number_of_chnl_off,pdde_number_of_chnl_on,pdde_most_use_chnl,pdde_cop_c_utilization_diversity,pdde_cop_c_most_use,pd_c_difference,cop_u_chnl_diversity,cop_u_number_of_chnl_off,cop_u_number_of_chnl_on,cop_u_cop_c_utilization_diversity,cop_u_cop_c_most_use,A01,A02,A03,A04,A05,A06,B01,C01,C02,D01,D02,E01,sum_use_pdde,sum_use_cop_u,sum_use,recency,frequency,monetary,R,F,M,RFMscore,weekend_holiday_use,buy_ct_sum,most_buy_cop_u,lpay_use_status
0,M430112881,67.0,우유,Z17014,Z17,8073.0,175000.0,38,47376.578947,5.868421,10137.342857,6870.746269,7329.720930,70,67,86,13.894737,0.282511,7578.611111,3958.000000,8589.440678,16350.000000,12077.959184,3806.818182,6077.969697,36,20,59,4,49,22,33,20210220,17,sat,패션잡화,918670.0,155.0,0.0,0.0,12.517937,61.707175,2.650224,67.798206,1.0,222.0,0.0,오프라인,3.0,A03,117.0,1.0,1.0,0.0,1.0,D01,18.0,64.0,140.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,222.0,1.0,223,528,223,1800310.0,4,5,4,435,223,319.0,A02,Lpay_X
1,M506355556,31.0,임대매출,Z17004,Z17,33155.0,199000.0,14,151567.857143,4.571429,45270.000000,9263.548387,58904.800000,8,31,25,36.857143,0.343750,95548.888889,4550.000000,52536.363636,35512.727273,9173.225806,0.000000,0.000000,9,2,11,11,31,0,0,20210211,18,thu,남성의류,781210.0,40.0,0.0,0.0,4.740625,69.421875,0.121875,85.234375,1.0,55.0,0.0,오프라인,3.0,A01,35.0,1.0,9.0,0.0,2.0,D02,29.0,24.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,5.0,0.0,55.0,9.0,64,516,64,2121950.0,2,3,4,335,64,66.0,D02,Lpay_X
2,M900002349,33.0,요구르트,Z10024,Z10,22617.0,460000.0,14,145393.571429,6.428571,23850.789474,52458.571429,10388.421053,38,14,38,37.714286,0.666667,23488.888889,0.000000,29113.392857,7240.000000,0.000000,6782.857143,8380.000000,9,0,56,4,0,7,14,20210508,16,sat,남성의류,549660.0,15.0,0.0,0.0,11.538889,70.732222,0.780000,91.011111,1.0,90.0,0.0,오프라인,2.0,A02,42.0,0.0,0.0,0.0,0.0,정보없음,17.0,73.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90.0,0.0,90,528,90,2035510.0,4,4,4,400,90,107.0,정보없음,Lpay_X
3,M694209751,106.0,스낵류,Z16009,Z16,20355.0,3100000.0,55,158032.072727,7.763636,10824.674074,36700.345679,9884.438462,135,162,130,9.600000,0.524590,21886.250000,9931.372727,33946.582011,14433.714286,3492.136364,7749.666667,3621.866667,8,110,189,35,22,48,15,20210116,14,sat,계절가전,756839.0,67.0,0.0,0.0,11.564637,57.493911,2.298595,40.365340,1.0,419.0,0.0,오프라인,3.0,A02,206.0,1.0,8.0,0.0,2.0,D01,83.0,201.0,135.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,1.0,0.0,419.0,8.0,427,528,427,8691764.0,4,5,5,485,427,538.0,D01,Lpay_Offline
4,M123475113,20.0,맥주,Z17004,Z17,13024.0,143040.0,11,47360.909091,3.636364,3945.000000,21647.894737,6007.692308,8,19,13,28.727273,0.425000,3357.500000,6231.666667,6081.764706,0.000000,0.000000,39258.888889,0.000000,8,6,17,0,0,9,0,20210129,12,sat,남성의류,315430.0,8.0,0.0,0.0,5.857500,53.430000,0.335000,60.875000,1.0,40.0,0.0,오프라인,2.0,A02,23.0,0.0,0.0,0.0,0.0,정보없음,6.0,34.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0,40,316,40,520970.0,1,2,2,185,40,53.0,정보없음,Lpay_X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18633,M781013992,0.0,정보없음,정보없음,정보없음,10200.0,23600.0,2,20400.000000,2.000000,0.000000,0.000000,10200.000000,0,0,4,0.500000,0.000000,0.000000,0.000000,0.000000,0.000000,5733.333333,0.000000,23600.000000,0,0,0,0,3,0,1,20210506,14,thu,정보없음,0.0,0.0,0.0,0.0,15.250000,50.900000,0.025000,51.500000,0.0,0.0,0.0,오프라인,0.0,정보없음,0.0,1.0,4.0,0.0,1.0,C02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0,4,405,4,40800.0,1,1,1,100,4,0.0,C02,Lpay_X
18634,M470873834,0.0,정보없음,정보없음,정보없음,3000.0,3000.0,1,3000.000000,1.000000,3000.000000,0.000000,0.000000,1,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3000.000000,0.000000,0,0,0,0,0,1,0,20210622,17,tue,정보없음,3000.0,1.0,0.0,0.0,22.800000,67.900000,0.000000,33.000000,0.0,0.0,0.0,오프라인,0.0,정보없음,0.0,1.0,1.0,0.0,1.0,C02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1,521,1,3000.0,3,1,1,130,1,0.0,C02,Lpay_X
18635,M226271405,0.0,정보없음,정보없음,정보없음,8600.0,8600.0,1,8600.000000,1.000000,8600.000000,0.000000,0.000000,1,0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8600.000000,0.000000,0.000000,0,0,0,0,1,0,0,20210225,0,thu,정보없음,0.0,0.0,0.0,0.0,2.500000,86.600000,17.000000,22.000000,0.0,0.0,0.0,오프라인,0.0,정보없음,0.0,1.0,1.0,0.0,1.0,D01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1,124,1,8600.0,1,1,1,100,1,0.0,D01,Lpay_X
18636,M999492154,0.0,정보없음,정보없음,정보없음,10300.0,10300.0,1,10300.000000,1.000000,0.000000,0.000000,10300.000000,0,0,1,0.000000,1.000000,0.000000,0.000000,10300.000000,0.000000,0.000000,0.000000,0.000000,0,0,1,0,0,0,0,20210109,17,sat,정보없음,10300.0,1.0,0.0,0.0,-12.200000,46.300000,0.000000,33.000000,0.0,0.0,0.0,오프라인,0.0,정보없음,0.0,1.0,1.0,0.0,1.0,D02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1,8,1,10300.0,1,1,1,100,1,0.0,D02,Lpay_X
18637,M701243523,0.0,정보없음,정보없음,정보없음,13000.0,13000.0,1,13000.000000,1.000000,0.000000,13000.000000,0.000000,0,1,0,0.000000,0.000000,13000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,0,0,0,0,0,0,20210618,12,fri,정보없음,0.0,0.0,13000.0,1.0,20.000000,92.100000,6.300000,32.000000,0.0,0.0,0.0,온라인,0.0,정보없음,0.0,1.0,0.0,1.0,1.0,C01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1,517,1,13000.0,2,1,1,115,1,0.0,C01,Lpay_X

In [4]:
print(features3_te.shape)
display(features3_te)

(3616, 82)

,cust,mpd_nunique,favorite_pd,favorite_zon,favorite_loc,mean_buy_am,max_buy_am,num_visit,day_sum_buy_am,day_count_buy_am,buy_mean_end,buy_mean_middle,buy_mean_begin,buy_count_end,buy_count_middle,buy_count_begin,buy_cycle,visit_weekend_ratio,fri_mean,mon_mean,sat_mean,sun_mean,thu_mean,tue_mean,wed_mean,fri_count,mon_count,sat_count,sun_count,thu_count,tue_count,wed_count,most_buying_day,most_buying_hour,most_buying_weekday,off_hot_time_buy_am,off_hot_time_buy_count,on_hot_time_buy_am,on_hot_time_buy_count,mean_temperature,mean_huminity,mean_rainfall,mean_atmosphere,pdde_chnl_diversity,pdde_number_of_chnl_off,pdde_number_of_chnl_on,pdde_most_use_chnl,pdde_cop_c_utilization_diversity,pdde_cop_c_most_use,pd_c_difference,cop_u_chnl_diversity,cop_u_number_of_chnl_off,cop_u_number_of_chnl_on,cop_u_cop_c_utilization_diversity,cop_u_cop_c_most_use,A01,A02,A03,A04,A05,A06,B01,C01,C02,D01,D02,E01,sum_use_pdde,sum_use_cop_u,sum_use,recency,frequency,monetary,R,F,M,RFMscore,weekend_holiday_use,most_expensive,buy_ct_sum,most_buy_cop_u,lpay_use_status
0,M099969868,3.0,냉동간편식,Z17018,Z17,7570.0,15000.0,2,15140.000000,2.000000,0.000000,7570.000000,0.000000,0,4,0,49.500000,0.750000,0.000000,0.000000,0.000000,7493.333333,0.000000,7800.000000,0.000000,0,0,0,3,0,1,0,20210815,17,sun,22480.0,3.0,0.0,0.0,26.000000,61.300000,0.000000,15.500000,1.0,3.0,0.0,오프라인,1.0,A01,3.0,1.0,1.0,0.0,1.0,D01,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,1.0,4,813,4,30280.0,2,1,1,115,4,0,3.0,0,Lpay_X
1,M421772848,30.0,일반담배,Z04003,Z04,5297.0,19459.0,22,12761.181818,2.409091,5370.714286,6338.666667,4603.166667,14,15,24,10.045455,0.301887,5041.066667,5206.250000,5100.000000,5787.500000,4902.500000,4895.000000,6198.333333,15,8,8,8,4,4,6,20210709,19,fri,124716.0,22.0,0.0,0.0,23.705660,67.000000,5.003774,21.698113,1.0,50.0,0.0,오프라인,4.0,A04,31.0,1.0,3.0,0.0,1.0,D01,3.0,2.0,21.0,24.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,50.0,3.0,53,829,53,280746.0,5,4,3,365,53,0,64.0,0,Lpay_X
2,M846905359,3.0,모바일상품권,점포없음,Z10,41905.0,85000.0,12,69841.666667,1.666667,15800.000000,85000.000000,29162.500000,6,6,8,16.833333,0.300000,50000.000000,50000.000000,29000.000000,4860.000000,65700.000000,0.000000,54400.000000,1,4,1,5,4,0,5,20210829,17,sun,7300.0,3.0,100000.0,2.0,25.655000,79.910000,4.175000,27.850000,2.0,4.0,11.0,온라인,3.0,A06,5.0,1.0,5.0,0.0,2.0,D02,1.0,0.0,0.0,3.0,0.0,11.0,0.0,0.0,0.0,1.0,4.0,0.0,15.0,5.0,20,805,20,838100.0,1,2,4,285,20,0,16.0,0,Lpay_Online
3,M742233311,53.0,레토르트,Z10044,Z10,6342.0,39600.0,19,58083.157895,9.157895,6955.909091,5578.545455,6371.132075,66,55,53,11.578947,0.235632,6424.750000,6317.000000,5648.529412,4757.142857,3186.666667,7937.916667,6435.000000,40,30,34,7,3,24,36,20210827,20,fri,264730.0,35.0,0.0,0.0,25.538506,82.407471,6.996552,27.275862,1.0,172.0,0.0,오프라인,1.0,A02,83.0,1.0,2.0,0.0,1.0,D01,0.0,172.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,172.0,2.0,174,824,174,1103580.0,3,5,4,420,174,0,204.0,0,Lpay_X
4,M118308498,36.0,식당,Z06009,Z06,6554.0,33000.0,8,53252.625000,8.125000,7752.000000,7062.157895,5953.333333,10,19,36,27.625000,0.630769,2940.000000,0.000000,6515.454545,7062.157895,10062.500000,4552.307692,0.000000,3,0,22,19,8,13,0,20210815,18,sat,159781.0,28.0,0.0,0.0,24.246154,76.718462,6.873846,13.584615,1.0,63.0,0.0,오프라인,1.0,A02,47.0,1.0,2.0,0.0,1.0,D01,0.0,63.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,63.0,2.0,65,823,65,426021.0,3,4,3,335,65,0,71.0,0,Lpay_X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3611,M943754955,45.0,냉장간편식,Z10041,Z10,6277.0,167200.0,12,52831.916667,8.416667,3545.750000,14620.000000,4267.466667,20,21,60,18.833333,0.376238,0.000000,7750.333333,7854.000000,9829.121212,5271.764706,3177.307692,3872.533333,0,3,5,33,17,13,30,20210704,13,sun,126911.0,25.0,0.0,0.0,22.605941,85.400000,13.884158,16.554455,1.0,98.0,0.0,오프라인,3.0,A03,65.0,1.0,3.0,0.0,1.0,D01,2.0,11.0,85.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,98.0,3.0,101,829,101,633983.0,5,5,4,450,101,0,109.0,D01,Lpay_X
3612,M187531769,40.0,냉장간편식,Z10027,Z10,6824.0,50000.0,5,126929.000000,18.600000,6130.703125,0.000000,8354.482759,64,0,29,43.800000,0.311828,0.000000,0.000000,8354.482759,0.000000,8291.428571,4688.076923,6433.125000,0,0,29,0,14,26,24,20210703,17,sat,398250.0,65.0,0.0,0.0,25.317204,75.982796,13.335484,24.537634,1.0,93.0,0.0,오프라인,2.0,A02,53.0,0.0,0.0,0.0,0.0,0,3.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,93.0,0.0,93,821,93,634645.0,3,5,4,420,93,0,112.0,0,Lpay_X
3613,M555730969,62.0,요구르트,Z10041,Z10,5419.0,36490.0,22,41384.363636,7.636364,4912.888889,4400.379747,7766.954545,45,79,44,10.227273,0.267857,5478.551724,4818.717949,6464.285714,4769.411765,4527.500000,7025.000000,0.000000,58,39,28,17,16,10,0,20210917,10,fri,115760.0,25.0,0.0,0.0,26.082738,73.808929,5.312500,25.821429,1.0,164.0,0.0,오프라인,2.0,A02,87.0,1.0,4.0,0.0,1.0,D01,0.0,159.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,164.0,4.0,168,826,168,910456.0,4,5,4,435,168,0,200.0,0,Lpay_X
3614,M103649386,44.0,가공유,Z11016,Z11,6182.0,89800.0,20,37094.800000,6.000000,3925.294118,9133.911111,4814.878049,34,45,41,11.200000,0.458333,3485.333333,11349.230769,5713.658537,3825.714286,5637.733333,0.000000,2461.111111,15,26,41,14,15,0,9,20210703,18,sat,542236.0,72.0,0.0,0.0,24.792500,76.649167,14.875000,14.108333,1.0,116.0,0.0,오프라인,2.0,A02,61.0,1.0,4.0,0.0,1.0,D01,0.0,100.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,116.0,4.0,120,826,120,741896.0,4,5,4,435,120,0,169.0,0,Lpay_X
3615,M026680290,54.0,아이스크림,Z04008,Z04,3326.0,18590.0,23,28197.652174,8.478261,3142.848485,3015.977778,4350.769231,66,90,39,9.391304,0.153846,2716.383562,4114.035714,3270.833333,6029.500000,3213.928571,4428.571429,3427.241379,73,28,24,6,28,7,29,20210827,19,fri,374045.0,112.0,0.0,0.0,25.486667,63.680513,1.698974,27.235897,2.0,183.0,11.0,오프라인,2.0,A03,87.0,1.0,1.0,0.0,1.0,D01,0.0,0.0,167.0,27.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,194.0,1.0,195,825,195,648546.0,4,5,4,435,195,0,231.0,0,Lpay_Online

In [5]:
features12_tr.drop('cust',axis=1,inplace=True)
features3_te.drop('cust',axis=1,inplace=True)

# Pycaret

In [6]:
exp_clf = setup(data = features12_tr, target = 'lpay_use_status', session_id=123)

In [7]:
best_model = compare_models(sort = 'AUC')

# Ensemble Model

In [9]:
best_model_5 = compare_models(sort = 'AUC',n_select=5)
blender_5 = blend_models(best_model_5)

In [ ]:
final_model = finalize_model(blender_5)

In [34]:
prediction = predict_model(final_model, data = features3_te)

In [35]:
prediction

,mpd_nunique,favorite_pd,favorite_zon,favorite_loc,mean_buy_am,max_buy_am,num_visit,day_sum_buy_am,day_count_buy_am,buy_mean_end,...,F,M,RFMscore,weekend_holiday_use,most_expensive,buy_ct_sum,most_buy_cop_u,lpay_use_status,Label,Score
0,3.0,냉동간편식,Z17018,Z17,7570.0,15000.0,2,15140.000000,2.000000,0.000000,...,1,1,115,4,0,3.0,0,3,Lpay_X,0.9715
1,30.0,일반담배,Z04003,Z04,5297.0,19459.0,22,12761.181818,2.409091,5370.714286,...,4,3,365,53,0,64.0,0,3,Lpay_X,0.7464
2,3.0,모바일상품권,점포없음,Z10,41905.0,85000.0,12,69841.666667,1.666667,15800.000000,...,2,4,285,20,0,16.0,0,2,Lpay_Online,0.6124
3,53.0,레토르트,Z10044,Z10,6342.0,39600.0,19,58083.157895,9.157895,6955.909091,...,5,4,420,174,0,204.0,0,3,Lpay_X,0.8527
4,36.0,식당,Z06009,Z06,6554.0,33000.0,8,53252.625000,8.125000,7752.000000,...,4,3,335,65,0,71.0,0,3,Lpay_X,0.8734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3611,45.0,냉장간편식,Z10041,Z10,6277.0,167200.0,12,52831.916667,8.416667,3545.750000,...,5,4,450,101,0,109.0,D01,3,Lpay_X,0.7111
3612,40.0,냉장간편식,Z10027,Z10,6824.0,50000.0,5,126929.000000,18.600000,6130.703125,...,5,4,420,93,0,112.0,0,3,Lpay_X,0.9467
3613,62.0,요구르트,Z10041,Z10,5419.0,36490.0,22,41384.363636,7.636364,4912.888889,...,5,4,435,168,0,200.0,0,3,Lpay_X,0.6714
3614,44.0,가공유,Z11016,Z11,6182.0,89800.0,20,37094.800000,6.000000,3925.294118,...,5,4,435,120,0,169.0,0,3,Lpay_X,0.6088
3615,54.0,아이스크림,Z04008,Z04,3326.0,18590.0,23,28197.652174,8.478261,3142.848485,...,5,4,435,195,0,231.0,0,2,Lpay_X,0.4438

In [71]:
ldf = pd.get_dummies(prediction['Label'])
ldf['Lpay_Offline'] = ldf['Lpay_Offline']*prediction['Score']
ldf['Lpay_On/Offline'] = ldf['Lpay_On/Offline']*prediction['Score']
ldf['Lpay_Online'] = ldf['Lpay_Online']*prediction['Score']
ldf['Lpay_X'] = ldf['Lpay_X']*prediction['Score']
ldf

      Lpay_Offline  Lpay_On/Offline  Lpay_Online  Lpay_X
0              0.0              0.0       0.0000  0.9715
1              0.0              0.0       0.0000  0.7464
2              0.0              0.0       0.6124  0.0000
3              0.0              0.0       0.0000  0.8527
4              0.0              0.0       0.0000  0.8734
...            ...              ...          ...     ...
3611           0.0              0.0       0.0000  0.7111
3612           0.0              0.0       0.0000  0.9467
3613           0.0              0.0       0.0000  0.6714
3614           0.0              0.0       0.0000  0.6088
3615           0.0              0.0       0.0000  0.4438

[3616 rows x 4 columns]

In [72]:
ldf['ms'] = 1-prediction['Score']
ldf['msv'] = ldf['ms']/4

In [73]:
ldf

      Lpay_Offline  Lpay_On/Offline  Lpay_Online  Lpay_X      ms       msv
0              0.0              0.0       0.0000  0.9715  0.0285  0.007125
1              0.0              0.0       0.0000  0.7464  0.2536  0.063400
2              0.0              0.0       0.6124  0.0000  0.3876  0.096900
3              0.0              0.0       0.0000  0.8527  0.1473  0.036825
4              0.0              0.0       0.0000  0.8734  0.1266  0.031650
...            ...              ...          ...     ...     ...       ...
3611           0.0              0.0       0.0000  0.7111  0.2889  0.072225
3612           0.0              0.0       0.0000  0.9467  0.0533  0.013325
3613           0.0              0.0       0.0000  0.6714  0.3286  0.082150
3614           0.0              0.0       0.0000  0.6088  0.3912  0.097800
3615           0.0              0.0       0.0000  0.4438  0.5562  0.139050

[3616 rows x 6 columns]

In [74]:
ldf.loc[ldf['Lpay_Offline']==0,'Lpay_Offline'] = ldf['msv']
ldf.loc[ldf['Lpay_On/Offline']==0,'Lpay_On/Offline'] = ldf['msv']
ldf.loc[ldf['Lpay_Online']==0,'Lpay_Online'] = ldf['msv']
ldf.loc[ldf['Lpay_X']==0,'Lpay_X'] = ldf['msv']

In [75]:
ldf = ldf.iloc[:,:4]
ldf

      Lpay_Offline  Lpay_On/Offline  Lpay_Online  Lpay_X
0         0.007125         0.007125     0.007125  0.9715
1         0.063400         0.063400     0.063400  0.7464
2         0.096900         0.096900     0.612400  0.0969
3         0.036825         0.036825     0.036825  0.8527
4         0.031650         0.031650     0.031650  0.8734
...            ...              ...          ...     ...
3611      0.072225         0.072225     0.072225  0.7111
3612      0.013325         0.013325     0.013325  0.9467
3613      0.082150         0.082150     0.082150  0.6714
3614      0.097800         0.097800     0.097800  0.6088
3615      0.139050         0.139050     0.139050  0.4438

[3616 rows x 4 columns]

In [77]:
ldf.iloc[:,0] = ldf.iloc[:,0]+(1-ldf.sum(axis=1))

In [79]:
test_target = features3_te['lpay_use_status']
roc_auc_score(test_target,ldf,multi_class='ovr',average='weighted')

0.7776614826923702

In [80]:
ldf['cust'] = pd.read_csv('../Data/features3_te.csv').cust
ldf

      Lpay_Offline  Lpay_On/Offline  Lpay_Online  Lpay_X        cust
0          0.01425         0.007125     0.007125  0.9715  M099969868
1          0.12680         0.063400     0.063400  0.7464  M421772848
2          0.19380         0.096900     0.612400  0.0969  M846905359
3          0.07365         0.036825     0.036825  0.8527  M742233311
4          0.06330         0.031650     0.031650  0.8734  M118308498
...            ...              ...          ...     ...         ...
3611       0.14445         0.072225     0.072225  0.7111  M943754955
3612       0.02665         0.013325     0.013325  0.9467  M187531769
3613       0.16430         0.082150     0.082150  0.6714  M555730969
3614       0.19560         0.097800     0.097800  0.6088  M103649386
3615       0.27810         0.139050     0.139050  0.4438  M026680290

[3616 rows x 5 columns]

In [81]:
ldf.to_csv('../3.로티로리_데이터 및 모델 세이브 파일/Pycaret_pred_df.csv',index=False)

In [82]:
save_model(final_model, '../3.로티로리_데이터 및 모델 세이브 파일/Pycaret_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[],
                                       target='lpay_use_status',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 nume...
                                                              learning_rate=0.300000012,
                                                              max_bin=256,
                                                              max_cat_to_onehot=4,
                                                              max_delta_step=0,
                                                              max_depth=6,
                                                              max_leaves=0,
                                                              min_child_weight=1,
                                                              missing=nan,
                                                              monotone_constraints='()',
                                                              n_estimators=100,
                                                              n_jobs=-1,
                                                              num_parallel_tree=1,
                                                              objective='multi:softprob',
                                                              predictor='auto',
                                                              random_state=123,
                                                              reg_alpha=0, ...))],
                                   flatten_transform=True, n_jobs=-1,
                                   verbose=False, voting='soft',
                                   weights=None)]],
          verbose=False),
 '../models/Pycaret_model.pkl')